server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/icoreman/spring-cloud-config-demo1.git #GitHub上面的git仓库名字
 

